#!/bin/bash
#SBATCH -p dlc 
#SBATCH --gres=gpu:4
#SBATCH -N 1
#SBATCH -c 16
#SBATCH -t 72:00:00
#SBATCH --error=%J.mu.out ## stderr file name(The %J will print job ID number)
#SBATCH --output=%J.mu.out ## stdout file name(The %J will print job ID number)    

#FASTA=GNE_homotetramer.fasta
FASTA=GNE_homodimer.fasta

# If a command-line argument was provided, use it instead
if [ -n "$1" ]; then
    FASTA="$1"
    echo "+++++ Using FASTA file provided as argument: ${FASTA}"
else
    echo "----- No FASTA argument provided. Using default: ${FASTA}"
fi
echo ""


# Expected location of the FASTA file
FASTA_PATH="./AF_inputs/${FASTA}"

# Check that the file exists
if [ ! -f "${FASTA_PATH}" ]; then
    echo "ERROR: FASTA file not found: ${FASTA_PATH}"
    exit 1
fi

echo "Confirmed FASTA file exists: ${FASTA_PATH}"
echo ""



echo "======================================================="
echo "!!! This script id for MULTIMER sequence only !!! (af2 data source updated 25 JAN 2026 to /users/public_data/AlphaFoldMulti/alphafold_data1122)."
echo "!!!!!!!!!!!!!!----  OPTION MULTIMER  ----!!!!!!!!!!!!!!!!!!!!!"
echo ""
echo "======================================================="
echo ""
echo "Starting JOB ${SLURM_JOBID} for the input ${FASTA}  at $(date)"
echo "======================================================="
echo ""
echo ""
echo "The start direstoty is $(pwd)"

echo "======================================================="
echo "Using sequence file $FASTA"
echo "======================================================="

echo ""
echo ""
echo "The start direstoty is $(pwd)"

#BASEDIR=/users/dchelouche/nromanenk/rachel
BASEDIR="$(pwd)"

echo "The value for the base directory: BASEDIR=$BASEDIR"

# KOSLOFFDIR=/users/kosloff
ALPHAFOLD_DATA_DIR=/users/public_data/AlphaFoldMulti/alphafold_data1122
# From kosloff group, copied previously by Oleg (apr 2025)
# ALPHAFOLD_DATA_DIR=/users/kosloff/alphafold_data



OUTPUTS=${BASEDIR}/woutputs/${SLURM_JOBID}

mounts="${BASEDIR}:/mount,${ALPHAFOLD_DATA_DIR}:/data,${OUTPUTS}:/outputs,${BASEDIR}/AF_inputs/:/AF_inputs"

RUNOPTS="--model_preset=multimer \
	--num_multimer_predictions_per_model=1 \
	--fasta_paths=/AF_inputs/${FASTA} \
	--output_dir=/outputs --data_dir=/data/ \
	--mgnify_database_path=/data/mgnify/mgy_clusters_2018_12.fa \
	--template_mmcif_dir=/data/pdb_mmcif/mmcif_files/ \
	--max_template_date=2020-05-14 \
	--obsolete_pdbs_path=/data/pdb_mmcif/obsolete.dat \
	--use_gpu_relax=False \
	--bfd_database_path=/data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
	--uniref90_database_path=/data/uniref90/uniref90.fasta \
	--uniclust30_database_path=/data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
        --pdb_seqres_database_path=/data/pdb_seqres/pdb_seqres.txt \
        --uniprot_database_path=/data/uniprot/uniprot.fasta"

srun bash -c "mkdir $OUTPUTS"

echo "======================================================="
echo "Starting JOB ${SLURM_JOBID} for input ${FASTA}  at $(date)"
echo "======================================================="


srun -l \
    --container-image=${BASEDIR}/AF_image.sqsh \
    --container-mounts=${mounts} \
    --container-workdir=/app/alphafold \
    --no-container-entrypoint \
    python /app/alphafold/run_alphafold.py $RUNOPTS
    
echo "======================================================="
echo "JOB ${SLURM_JOBID} completed at $(date)"
echo "======================================================="


OR_OUTPUTS=${BASEDIR}/OR_OUTPUTS
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Alphafold2 output processing at ${SLURM_JOBID}  the time: $(date)"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

# python3 output_name_update.py -i=137783 -p=./woutputs
# python3 output_name_update.py -i=137783 -p=./woutputs -o=./or_outputs
python3 output_name_update.py -i=${SLURM_JOBID} -p=${BASEDIR}/woutputs -o=OR_OUTPUTS

echo "           "
echo "           "
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Alphafold2 postprocessing completed at time: $(date)"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "PLDDT (multimer) scores preparation at ${SLURM_JOBID}  the time: $(date)"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo ""
echo "Doing plddt for ${SLURM_JOBID}_processed pdb files"
# python3 plddt_scorer.py  -i ./woutputs/156010_processed/
# python3 plddt_scorer.py  -i ./OR_OUTPUTS/HsOR343/
python3 plddt_scorer.py --input=./woutputs/${SLURM_JOBID}_processed/

echo "========================================================================================"
echo "Going to get/update plddt scores for OR_NAME located pdb files at ${OR_OUTPUTS}"

mapfile -t this_job_or_names < <(find "./woutputs/${SLURM_JOBID}" -mindepth 1 -maxdepth 1 -type d ! -name ".*"  -printf "%f\n")

echo ".. got or_names with mapfile..: ${or_names[@]}"
echo "========================================================================================"

echo ""
for or_name in "${this_job_or_names[@]}"; do
    echo "--------------------------------------------------------------------"
    echo "Processing $or_name with plddt_scorer.py"
    python3 plddt_scorer.py  -i $OR_OUTPUTS/$or_name
    echo "--------------------------------------------------------------------"
    echo ""
done


echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "DONE PLDDT scores for ${SLURM_JOBID} at the time: $(date), MULTIMER SCRIPT COMPLETED"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"


