#!/bin/bash
#SBATCH -p dlc
#SBATCH --gres=gpu:1
#SBATCH -N 1
#SBATCH -c 16
#SBATCH -t 48:00:00
#SBATCH --error=%J.splitmono.out
#SBATCH --output=%J.splitmono.out

FASTA=HsORs_for_several_monomers_predictions.fasta
#FASTA=dm1.fasta

echo "======================================================="
echo "!!! This script can handle multiple monomer sequences in one file !!! (af2 data source updated 25 JAN 2026 to /users/public_data/AlphaFoldMulti/alphafold_data1122)."
echo ""
echo "======================================================="
echo ""
echo "Starting JOB ${SLURM_JOBID} for multiple mono input ${FASTA}  at $(date)"
echo "======================================================="
echo ""
echo ""
echo "The start direstoty is $(pwd)"

#BASEDIR=/users/dchelouche/nromanenk/rachel
BASEDIR="$(pwd)"

echo "The value for the base directory: BASEDIR=$BASEDIR"

# KOSLOFFDIR=/users/kosloff
ALPHAFOLD_DATA_DIR=/users/public_data/AlphaFoldMulti/alphafold_data1122
# From kosloff group, copied previously by Oleg (apr 2025)
# ALPHAFOLD_DATA_DIR=/users/kosloff/alphafold_data

OUTPUTS=${BASEDIR}/woutputs/${SLURM_JOBID}
echo ""
echo "Creating the output directory SUBMONO for the alphafold2 outputs"
echo ""

srun bash -c "mkdir $OUTPUTS"

mounts="${BASEDIR}:/mount,${ALPHAFOLD_DATA_DIR}:/data,${OUTPUTS}:/outputs,${BASEDIR}/AF_inputs/:/AF_inputs"


echo ""
echo "Creating the output directory SUBMONO for the split files"
echo ""
srun bash -c "mkdir -p ${BASEDIR}/AF_inputs/SUBMONO"

echo "== Call the Python script and capture the output file names "
SPLITTED_FILES=$(srun python3 fasta_splitter.py "-i=${BASEDIR}/AF_inputs/${FASTA}" "-o=${BASEDIR}/AF_inputs/SUBMONO")

# Output the list of split files
echo "== Split files: $SPLITTED_FILES"

# Optionally, you can loop through the split files and perform additional operations
for file in $SPLITTED_FILES; do
    echo "Start processing file: $file  at $(date)"
    
    RUNOPTS="--model_preset=monomer \
	--num_multimer_predictions_per_model=1 \
        --fasta_paths=/AF_inputs/SUBMONO/${file} \
        --output_dir=/outputs --data_dir=/data/ \
        --mgnify_database_path=/data/mgnify/mgy_clusters_2018_12.fa \
        --template_mmcif_dir=/data/pdb_mmcif/mmcif_files/ \
        --max_template_date=2020-05-14 \
        --obsolete_pdbs_path=/data/pdb_mmcif/obsolete.dat \
        --use_gpu_relax=False \
        --bfd_database_path=/data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
        --uniref90_database_path=/data/uniref90/uniref90.fasta \
        --uniclust30_database_path=/data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
        --pdb70_database_path=/data/pdb70/pdb70"

    srun -l \
        --container-image=${BASEDIR}/AF_image.sqsh \
        --container-mounts=${mounts} \
        --container-workdir=/app/alphafold \
        --no-container-entrypoint \
        python /app/alphafold/run_alphafold.py $RUNOPTS

    echo "==="
    echo "End processing file: $file  at $(date)"
    echo "==="

done


echo "======================================================="
echo "JOB ${SLURM_JOBID} completed at $(date)"
echo "======================================================="
echo "           "
echo "           "

OR_OUTPUTS=${BASEDIR}/OR_OUTPUTS
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Alphafold2 output processing at ${SLURM_JOBID}  the time: $(date)"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

# python3 output_name_update.py -i=137783 -p=./woutputs
# python3 output_name_update.py -i=137783 -p=./woutputs -o=./or_outputs
python3 output_name_update.py -i=${SLURM_JOBID} -p=${BASEDIR}/woutputs -o=OR_OUTPUTS

echo "           "
echo "           "
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Alphafold2 postprocessing completed at time: $(date)"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"



echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "PLDDT scores preparation at ${SLURM_JOBID}  the time: $(date)"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo ""
echo "Doing plddt for ${SLURM_JOBID}_processed pdb files"
# python3 plddt_scorer.py  -i ./woutputs/156010_processed/
# python3 plddt_scorer.py  -i ./OR_OUTPUTS/HsOR343/
python3 plddt_scorer.py --input=./woutputs/${SLURM_JOBID}_processed/

echo "========================================================================================"
echo "Going to get/update plddt scores for OR_NAME located pdb files"

mapfile -t this_job_or_names < <(find "./woutputs/${SLURM_JOBID}" -mindepth 1 -maxdepth 1 -type d ! -name ".*"  -printf "%f\n")

echo ".. got or_names witth mapfile..: ${or_names[@]}"
echo "========================================================================================"

echo ""
for or_name in "${this_job_or_names[@]}"; do
    echo "--------------------------------------------------------------------"
    echo "Processing $or_name with plddt_scorer.py"
    python3 plddt_scorer.py  -i $OR_OUTPUTS/$or_name
    echo "--------------------------------------------------------------------"
    echo ""
done


echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "DONE PLDDT scores for ${SLURM_JOBID} at the time: $(date), SCRIPT COMPLETED"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"





